steps:
- name: node:20.12.1
  entrypoint: npm
  args: ['ci']
- name: node:20.12.1
  entrypoint: npx
  args: ['bundage', 'bns', 'backend/main_${_ENVIRONMENT}', 'main_bin', '-t', 'bin']
- name: 'node:20.12.1'
  entrypoint: npx
  args: ['bundage', 'bwa', '-ec', 'frontend/web/entries_${_ENVIRONMENT}.yaml', '-b', 'frontend/web', '-o', 'bin/static']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/web:latest', '-f', 'Dockerfile', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/${PROJECT_ID}/web:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'stop', '${_SERVER_NAME}', '--zone', '${_SERVER_ZONE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'start', '${_SERVER_NAME}', '--zone', '${_SERVER_ZONE}']
options:
  logging: CLOUD_LOGGING_ONLY
